[package]
name = "macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
axum = { workspace = true }
axum-extra = { workspace = true }
proc-macro2 = "1.0.104"
quote = "1.0.42"
syn = { version = "2.0.112", features = ["full"] }
